### ISSUE TITLE
설계

### ISSUE THREAD

**Issue by xodhksrjqnr** [xodhksrjqnr/toyProject-Smart#1]
step1.기본_구조_구현

- 기본 구조 설계
- 기본적인 기능을 갖춘 Domain 구현

**Comment by xodhksrjqnr** [comment]
step2.쇼핑몰_형태_구현

1. 검색 기능
    - 제품명을 이용한 검색
    
2. 제품 보여주기
    - 제품 상세 페이지
    - 카테고리, 검색 페이지
        - 필터[등록순(↓, ↑), 가격순(↓, ↑)]
        - 페이지네이션
    - 관리자 페이지
        - 제품 등록, 제품 수정, 제품삭제
        - 페이지네이션
       
3. 카테고리 분류
    - 상의 (A)
        - 후드 티셔츠 (A01)
        - 맨투맨 (A02)
    - 아우터 (B)
        - 코트  (B01)
        - 패딩 (B02)
    - 바지 (C)
        - 트레이닝 팬츠 (C01)
        - 숏 팬츠 (C02)
    - 신발 (D) 
        - 구두 (D01)
        - 운동화 (D02)

**Comment by presentKey** [comment]
step3.회원_기능_구현

1. 회원가입
     - 아이디, 패스워드
     - 이메일 인증
     - 생일, 폰 번호

2. 회원탈퇴
     - 이메일 인증
    
3. 로그인, 로그아웃
    - 아이디 찾기, 패스워드 찾기

5. 장바구니
     - 장바구니 추가, 삭제
  
6. 마이페이지 조회, 수정
   - 비밀번호 변경
      - 이메일 인증
   - 주문 조회
   - 주문 취소
